version: "3"

services:
  client:
    image: node:22.9-alpine
    restart: on-failure
    command: npm install && npm run build && node .output/server/index.mjs
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file: .env
    working_dir: /app
